version: '3'

services:
  db:
    image: postgres
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/task_app
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true
    stdin_open: true
